wandb_version: 1

num_classes:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
image_size:
  desc: null
  value: 224
image_channels:
  desc: null
  value: 3
earlystopping_patience:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.001
initial_epochs:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720282605
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.12.3
      5: 0.17.3
      8:
      - 1
      - 5
      13: linux-x86_64
