wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1720276893
    t:
      1:
      - 2
      - 3
      - 55
      - 105
      2:
      - 2
      - 3
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.12.3
      5: 0.17.3
      8:
      - 1
      - 5
      13: linux-x86_64
